### PR TITLE
Adding benchmark test for `async/await`.

### PR DESCRIPTION
**Pull request by sanjaiyan-dev**
Adding benchmark test for `async/await` :)

_Sorry if I made any mistakes :(_

### CODE REVIEW

**Review by RafaelGSS — CHANGES_REQUESTED** [review]
Could you elaborate on why you think that's needed? The idea of this repository is to benchmark fastify against other frameworks.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by sanjaiyan-dev** [comment]
> Could you elaborate on why you think that's needed? The idea of this repository is to benchmark fastify against other frameworks.

I thought this will help to view benchmark when we use fastify with modern `async/await` which is natively supported by fastify 🎉 And asynchronous route would perform little faster than synchronous route (not 💯 sure)

Extremely sorry if I made any mistake :(

**Comment by RafaelGSS** [comment]
> > Could you elaborate on why you think that's needed? The idea of this repository is to benchmark fastify against other frameworks.
> 
> I thought this will help to view benchmark when we use fastify with modern `async/await` which is natively supported by fastify tada And asynchronous route would perform little faster than synchronous route (not 100 sure)
> 
> Extremely sorry if I made any mistake :(

Don't be sorry, your intention is what matters here. We truly appreciate your Pull Request, any kind of improvement is very welcome. However, in my opinion, this one, in particular, doesn't fit the repository goal.

Nevertheless, if want to keep working on this project, check our [good first issues](https://www.fastify.io/contribute/) and don't hesitate in asking for help if you need it. We're available on [discord](https://github.com/fastify/fastify#ecosystem) too. Feel free to ping me there.

**Pull request closed without merging**
