### PR TITLE
Add AdonisJS

### PR DESCRIPTION
**Pull request by RomainLanz**
Hey there! 👋🏻 

This PR adds [AdonisJS](https://adonisjs.com/) Http server for benchmarking purpose.

I am not quite sure about some options in the `package.js` file, like the `extra` params.

AdonisJS comes by default with middleware enabled for example.

Let me know if I need to make any modification. 👍🏻

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Can you remove Node v14, v16 and v18 from the list of envs we support?

**Comment by RomainLanz** [comment]
> Can you remove Node v14, v16 and v18 from the list of envs we support?

I am not sure if you are asking me to modify something in this PR or make another PR that removes the outdated Node.js version from CI.

On a side note, if needed, I could send another PR to migrate from import assertion to import attribution.

**Comment by RomainLanz** [comment]
Small bump. 👋🏻

**Comment by mcollina** [comment]
Sorry for the long delay, I have a long queue of GitHub notifications to manage. CI was bumped, so you should be able to rebase now.

**Comment by RomainLanz** [comment]
No worries!

PR has been rebased. 👍🏻

**Comment by mcollina** [comment]
finally done! Sorry for the wait!

**Comment by mcollina** [comment]
finally done! Sorry for the wait!

**Pull request merged**
