### PR TITLE
update micro-router benchmark

### PR DESCRIPTION
**Pull request by dotcypress**
Speed up `micro-router` benchmark.

Related issue: [#41](https://github.com/fastify/benchmarks/issues/41)

### CODE REVIEW

**Comment by leo** [comment]
wow, great! is it intentional that the new package is called "micro-route" instead of "micro-router"?

**Comment by styfle** [comment]
Maybe it should be a separate benchmark? That way people can decide which router they want. Or will that make for too many options to choose from?

**Comment by aichholzer** [comment]
This is been left for a good while now... 🤔 
Will close this PR if nothing changes in the next few days.

**Comment by dotcypress** [comment]
@aichholzer `micro-route` moved to separated benchmark.

**Comment by mcollina** [comment]
@delvedor are you ok?

**Pull request merged**
