### PR TITLE
add hyper-express

### PR DESCRIPTION
**Pull request by dougg0k**

### CODE REVIEW

**Comment by mcollina** [comment]
I'm -1 to add this for the exact same reason we do not have uWebsocket.js. It's different C library than Node.js core.

**Comment by dougg0k** [comment]
It's based on it, but certainly has very decent API to use, and by no means barebones, it's has almost everything other APIs do. 

Also faster than fastify. Not because of that, right?

**Comment by dougwilson** [comment]
> Also faster than fastify. Not because of that, right?

No

**Comment by dougg0k** [comment]
@mcollina Care to explain the reasoning, what is the problem with being a different C lib?

**Comment by Eomm** [comment]
Let me share my opinion: it is not a generic HTTP framework. It is focused on speed over user experience.

What does it mean?

- our [benchmark does not support `uWebSockets`](https://github.com/uNetworking/uWebSockets/tree/master/benchmarks#common-benchmarking-mistakes)
- if you call a random `hyper-express`/`uWebSockets` server's route, you don't get a 404, you will get a `close connection`, you need to implement basic stuff by yourself
- `uWebSockets` is a perfect suite for a precise use case. That use case is not a generic web framework. `uWebSockets` does not implement middleware or hooks nor a plugin system. It is a low-level, high-speed, low-features web server.
- funny thing: you can start a fastify server and a `hyper-express` server on the same port because the WS and HTTP protocol can work together
- node.js updates do not solve HTTP issues the user may face. So all the Node.js documentation about HTTP is useless for an `uWebSockets` user. Moreover, any issue the user may face with the server should ask for support to the `uWebSockets` community. Note that the project is open source, but owned by a private company with a bus factor equal to 1**
- when you run `uWebSockets`, you are not running the Node.js HTTP server code. It communicates with V8 directly, bypassing the Node.js layer

Happy to learn something more by reading other opinions

Interesting readings:

- https://unetworkingab.medium.com/the-story-of-uws-so-far-493ac0c05ccb
- https://unetworkingab.medium.com/will-node-js-forever-be-the-sluggish-golang-f632130e5c7a

** https://github.com/uNetworking/uWebSockets.js/graphs/contributors

image

**Comment by dougg0k** [comment]
Hey @Eomm 

I understand, but mostly of what you said was to uWebsocket, not hyper-express which has more functionality built upon it, which improves on the DX. It has middleware support and more.

It should work on any debian based OS with node out of the box.

As for the random route, if you ask the maintainer he might add.

Thanks for your input though.

**Pull request closed without merging**
