### PR TITLE
build(deps-dev): bump standard from 12.0.1 to 16.0.3

### PR DESCRIPTION
**Pull request by Fdawgs**
Linted with latest version as well, which was causing #146 to fail

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Comment by Fdawgs** [comment]
@fastify/benchmarks mind reviewing this one please?

**Comment by RafaelGSS** [comment]
Can you resolve the conflicts?

**Comment by Fdawgs** [comment]
@RafaelGSS  moved over to #199  as i stupidly deleted the original branch >.<

**Pull request closed without merging**
