### PR TITLE
feat: add hrtime handles

### PR DESCRIPTION
**Pull request by zekth**
This allows to compute `process.hrtime` results (shown in ms) like:

```js
{
  '1-startup-routes-schema.js': { startup: 213.80812727272732, listen: 242.06124545454549 },
  '1-startup-routes.js': { startup: 230.8941714285714, listen: 243.2510095238095 },
  '10-startup-routes-schema.js': { startup: 210.97057272727272, listen: 242.81881818181822 },
  '10-startup-routes.js': { startup: 219.46089545454544, listen: 232.58262727272725 },
  '100-startup-routes-schema.js': { startup: 220.58468499999998, listen: 282.69149 },
  '100-startup-routes.js': { startup: 218.96986363636367, listen: 239.5788318181818 },
  '1000-startup-routes-schema.js': { startup: 248.63744166666666, listen: 634.4636583333335 },
  '1000-startup-routes.js': { startup: 239.46513529411763, listen: 337.505488235294 },
  '10000-startup-routes-schema.js': { startup: 427.5839, listen: 3375.9787999999994 },
  '10000-startup-routes.js': { startup: 420.83230000000003, listen: 1193.2728333333334 },
  'startup-listen.js': { startup: 210.83020909090916, listen: 220.50167727272728 }
}
```

Usage:
```bash
rm -rf metrics/*.txt && node metrics/startup.js && node metrics/process-results.js
```

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by RafaelGSS — COMMENTED** [review]
I feel that `listen` is also a startup time since the app is unaware of receiving requests, and the results make sense since `listen` owns `startup` time, and avvio only works after that.

**Review by RafaelGSS — APPROVED** [review]
I think that we can merge it and discuss in the target PR if we should keep the `benchmark.suite` or `hr.time` is enough. LGTM!

**Comment by zekth** [comment]
@RafaelGSS benchmark allows to run the scenario several times and we do the average of those results. So i think we should keep it but not rely on the results.

**Pull request merged**
