### PR TITLE
Added micro as benchmark

### PR DESCRIPTION
**Pull request by aboutlo**
fastify vs micro

benchmark settings:
```
? Do you want to run all benchmark tests? No
? How many connection you need? 100
? How many pipelining you need? 10
? How long does it takes? 5
```

hardware: 
- MacBook Pro (13-inch, 2016, Two Thunderbolt 3 ports)
- 2 GHz Intel Core i5
- 16 GB 1867 MHz LPDDR3

### CODE REVIEW

**Comment by StarpTech** [comment]
Is this really a fair comparison? If you look at the features https://github.com/zeit/micro#features you will recognize that micro is as the name suggests for micro tasks. It has no api, no router, no middleware. It's just a HTTP server with some transpiling for async / await support the rest is marketing.

**Comment by jsumners** [comment]
@StarpTech  The proposed benchmark does the exact same thing as the Fastify benchmark: return the object `{hello: 'world'}`. If the benchmarks actually exercised the features you are claiming Micro should have for the benchmarks to be "fair" then you would have a valid argument. As it is, just because Micro is faster doesn't make it unfair.

**Comment by cagataycali** [comment]
In this regard, we have brought the same standard by closing some of the basic features on both sides for the purpose of making the comparisons fair. There are no referrals in this library. In this way, I can not see a feature added to the standard library.

**Comment by StarpTech** [comment]
@jsumners you're right we just benchmark the case of responding a `{hello: 'world'}` object. We should definitely add some framework conditions otherwise any framework with name `X` will create a PR just to show that `{hello: 'world'}` respond faster than `Y`. If you think about it "Micro" is no web framework. 

Some conditions:
- Has to provide a router
- Has to provide a middleware
- Has to provide a plugin API

**Comment by cagataycali** [comment]
You can add micro-router in your example, then we can discuss about this :)

**Comment by mcollina** [comment]
I am +1 in adding this module. micro does almost nothing on top of http from core. It’s a good benchmark to beat.

As we did with Koa, we should add also a variant with a router.

**Comment by aboutlo** [comment]
happy to add the router variant

**Comment by aboutlo** [comment]
screen shot 2017-09-24 at 01 37 59

**Comment by cagataycali** [comment]
Wow, they are equal, Really?

**Comment by aboutlo** [comment]
@cagataycali, however, I got inconsistent results so if you can share the default settings I can run them again

**Comment by cagataycali** [comment]
These settings are enough for testing I think,
```
? Do you want to run all benchmark tests? No
? How many connection you need? 100
? How many pipelining you need? 10
? How long does it takes? 5
```

**Comment by jsumners** [comment]
As an aside, this PR is exactly why we need the benchmarks to output the numbers as a summary instead of an English sentence.

**Comment by cagataycali** [comment]
@jsumners I'm working on this, but PR's are welcome :)

**Comment by aboutlo** [comment]
@cagataycali then I used the default settings but if you use

```
? Do you want to run all benchmark tests? No
? How many connection you need? 200
? How many pipelining you need? 10
? How long does it takes? 5
```

I got this:

```
Both are awesome but fastify is 19.54% faster than micro-router
fastify request average is 20187.2
micro-router request average is 16887.2
```
or again this

```
node ./benchmark-compare.js 
? What's your first pick? fastify
? What's your second one? micro-router
fastify and micro-router both are fast!
```

+- ~20% it's a lot

**Comment by dougwilson** [comment]
So is this good to merge now? Or are there outstanding asks / objections?

**Comment by cagataycali** [comment]
Merged

**Pull request merged**
