### PR TITLE
Add uWebSockets.js benchmark

### PR DESCRIPTION
**Pull request by aadityataparia**
This PR adds benchmark for https://github.com/uNetworking/uWebSockets.js

### CODE REVIEW

**Comment by aichholzer** [comment]
@aadityataparia -Thank you for that.
Although it technically is a framework, I am not sure how fair it is to list it here, since it is, entirely, a whole different approach the Node's `http` (which all other modules in this benchmark use). Makes it almost like comparing apples to oranges.

@mcollina @delvedor what are your thoughts on this?

**Comment by aadityataparia** [comment]
Fair enough, I just wanted to test it against others, but merging it is upto you guys entirely. No problems here!

**Comment by aichholzer** [comment]
@aadityataparia -This PR is along the lines of [this thread](https://github.com/fastify/benchmarks/issues/53).

**Comment by aadityataparia** [comment]
Closing because of inactivity

**Pull request closed without merging**
