### PR TITLE
chore(benchmarks): update cron to run weekly

### PR DESCRIPTION
**Pull request by RafaelGSS**
Currently, we are updating the benchmarks once per month, I think that for track purposes would be better run everyday

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Eomm** [comment]
Would not it be too much for the git history?

**Comment by RafaelGSS** [comment]
30 commits per month, I don't think so

**Comment by mcollina** [comment]
I would prefer weekly.

**Review by Eomm — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
