### PR TITLE
feat: Adding the library mini-express-server library

### PR DESCRIPTION
**Pull request by josealejandro2928**
I added another library that I wrote.
"mini-express-library"

### CODE REVIEW

**Comment by Eomm** [comment]
Personal opinion:
I don't think the benchmark list should include a module published one week ago.

The list on the readme should provide value to the user to compare frameworks ready to use in production.

For the same reason, I think we should clean the list actually from:

- https://www.npmjs.com/package/galatajs
- https://www.npmjs.com/package/vapr
- https://www.npmjs.com/package/spirit
- https://www.npmjs.com/package/spirit-router
- https://www.npmjs.com/package/yeps

**Comment by Eomm** [comment]
@fastify/benchmarks opinion on my previous message?

**Comment by josealejandro2928** [comment]
I really wish my npm package could be included in the benchmarks, even
though it doesn't reach the fastify numbers, it has 100% compatibility with
express since I based it on the middleware pattern and therefore all
popular packages based on express middleware run, but I improved the
routing algorithm which allows it to have a higher performance in the
benchmarks for more complex schemes like api's that reach 100 endpoinds. It
is also faster than koa and hapi. I know it's young but this is my
contribution to open source. It could be included.

**Comment by RafaelGSS** [comment]
> @fastify/benchmarks opinion on my previous message?

+1

**Comment by aichholzer** [comment]
I agree with @Eomm.
Closing this PR.

**Pull request closed without merging**
