### PR TITLE
chore(restify): upgrade to 7.1.0

### PR DESCRIPTION
**Pull request by hekike**
Both are awesome but fastify is 17.7% faster than restify

 Both are awesome but restify is 44.63% faster than koa
 Both are awesome but restify is 55.73% faster than express
 Both are awesome but restify is 58.31% faster than hapi

 • fastify request average is 33734.4
 • restify request average is 28660.8
 • koa request average is 19816
 • express request average is 18404
 • hapi request average is 18104

Can we update this page: https://www.fastify.io/benchmarks/ ? ;)

### CODE REVIEW

**Comment by allevo** [comment]
LGTM

**Comment by hekike** [comment]
Thanks!

**Comment by hekike** [comment]
@mcollina when do you plan to update the website? I'm too excited :)

**Comment by mcollina** [comment]
This is what I got: https://github.com/fastify/fastify/pull/919.

Maybe I'm doing something wrong?

**Comment by averri** [comment]
> Both are awesome but fastify is 17.7% faster than restify
> 
> Both are awesome but restify is 44.63% faster than koa
> Both are awesome but restify is 55.73% faster than express
> Both are awesome but restify is 58.31% faster than hapi
> 
> • fastify request average is 33734.4
> • restify request average is 28660.8
> • koa request average is 19816
> • express request average is 18404
> • hapi request average is 18104
> 
> Can we update this page: https://www.fastify.io/benchmarks/ ? ;)

Hi @hekike, what is the server and operating system do you use to get these results? I'm running Express on Windows 10, the highest throughput I get is around 3500 requests per second, using a simple endpoint returning an empty string.

**Comment by hekike** [comment]
@averri 

Machine:
```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,2
  Processor Name:	Intel Core i7
  Processor Speed:	3.5 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	4 MB
  Memory:	16 GB
```

Do you use Node 10.x?

**Comment by averri** [comment]
@hekike, thanks for informing.

Yes, I'm using Node v10.15.3

**Comment by SeniorAlexander** [comment]
> @hekike, thanks for informing.
> 
> Yes, I'm using Node v10.15.3. It would be great if another user try to reproduce this test on their Windows machine.

Windows 10, 32 Gb RAM, i7-9700f, NodeJs v13.05.0 this is the result:

` autocannon -c 50 -d 30 -m POST http://localhost:4999
`

1) fastify request average is 1106k requests in 30.07s, 180 MB read
2) koa request average is 817k requests in 30.06s, 130 MB read
3) express request average is 612k requests in 30.06s, 140 MB read
4) restify request average is 601k requests in 30.05s, 104 MB read
5) hapi request average is 471k requests in 30.05s, 86.7 MB read

https://github.com/SeniorAlexander/node_servers

**Pull request merged**
