### PR TITLE
Adds benchmark Fastify + TRPC router adapter

### PR DESCRIPTION
**Pull request by giacomorebonato**
I am adding an example of Fastify using [TRPC and its Fastify adapter](https://trpc.io/docs/v9/fastify) for defining API routes.

It's my first contribution, I am checking if I am missing anything for the PR.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
What route would this expose?

**Comment by giacomorebonato** [comment]
It's exposing route `/` due to the empty string passed to `.query('')`.
May I add some comments to make it more clear?

Screenshot 2022-08-31 at 15 33 26

**Comment by mcollina** [comment]
Thanks, more comments explaining this would be very handy!

**Review by mcollina — APPROVED** [review]
lgtm

**Review by RafaelGSS — APPROVED** [review]

**Pull request merged**
