### PR TITLE
Adds uWebSockets server

### PR DESCRIPTION
**Pull request by streamich**
This PR adds uWebSockets server.

image

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jsumners** [comment]
Why is it fair to compare an HTTP framework with a Web Sockets framework?

**Comment by streamich** [comment]
@jsumners I guess you imply that `uWebSockets` library is a "Web Sockets framework". `uWebSockets` is a library which provides an HTTP server as well as a WebSocket server. The benchmark in this PR only tests the HTTP server part; I assume the WebSocket implementation of `uWebSocket` would be even faster. But that indeed would not be fair.

**Comment by Eomm** [comment]
It is a C++ server if I'm not wrong, so the comparison is tricky for the reader

**Comment by streamich** [comment]
@Eomm nope, it is JavaScript, you can see the route handler in this PR: https://github.com/fastify/benchmarks/blob/162467d8c8b8d28d22d97d6113bf23f672f8910f/benchmarks/uWebSockets.js

**Comment by Eomm** [comment]
The app var is not 😅

**Comment by streamich** [comment]
Essentially these benchmarks now are deceiving the reader, `uws` is about 2x faster than `fastify`, but the whole purpose of this repo is to promote `fastify`.

**Pull request closed without merging**
