### PR TITLE
Do not use globalmodules

### LINKED ISSUE #18: Do not rely on global-modules, but create a folder in process.cwd()
As titled

### LINKED ISSUE #20: include the version number of the framework in the result folder jsons

### PR DESCRIPTION
**Pull request by mcollina**
Fixes #20 
Fixes #18

### CODE REVIEW

**Comment by dougwilson** [comment]
Perhaps I was too fast. `benchmark-compare.js` probably should be changed to look in cwd too.

**Comment by mcollina** [comment]
Ouch, good finding.

**Comment by mcollina** [comment]
Updated

**Comment by cagataycali** [comment]
I saw to do in code, I did. I love this changes!

**Comment by cagataycali** [comment]
That's looking like this, 
screen shot 2017-09-12 at 17 24 43

**Comment by mcollina** [comment]
awesome!

**Pull request merged**
