### PR TITLE
Add: results folder into .gitignore

### PR DESCRIPTION
**Pull request by tinawng**
just putting back /results folder into .gitignore
see: https://github.com/fastify/benchmarks/pull/106#discussion_r373807047

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by jsumners — APPROVED** [review]
LGTM

**Review by Eomm — APPROVED** [review]
@fastify/benchmarks we need a merge power superhero 😄

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Pull request merged**
