### PR TITLE
server-base benchmarks

### PR DESCRIPTION
**Pull request by JamesKyburz**
This PR implements benchmarks for [server-base](https://github.com/JamesKyburz/server-base/tree/master/packages).

server-base is a small http server ideal for micro services (says the author=me with some bias :))

### CODE REVIEW

**Comment by aichholzer** [comment]
@JamesKyburz -Could you please provide a description of what this PR fixes/implements?
Thank you.

**Comment by JamesKyburz** [comment]
@aichholzer Sure and thanks for quick reply!

I have updated the description.

**Comment by aichholzer** [comment]
@JamesKyburz -Thank you.
LGTM.
@mcollina / @delvedor any comments? We might need to think about [this](https://github.com/fastify/benchmarks/issues/53) as well.
(@JamesKyburz please don't take the link above as personal. 🙏)

**Comment by JamesKyburz** [comment]
Great thx!

**Pull request merged**
